# Site settings
author: Danielle Torres
title: 
header-img: img/home-bg.png
email: cruz_danielle_torres@yahoo.com
copyright_name: Danielle Torres
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DCTorres1987

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
